# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e89e810d20670cbb9a3ac37f8fa3503229b3d54c8a7addbe6be3147af6c7126bec954f6f2bc935c008c400638ffddba9c22d7861d6843a34a22199447a45cff0

test:
  secret_key_base: 4bed9e0c19dacfa39f6f40a3176ead77d4b4e76474dbbd58e4c15375ecfc7de78ecd30572e08e4bd5b46febce80f39a52b65587927a863cad5111b0a340d8163

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
